from __future__ import annotations

from enum import Enum


class TransactionType(str, Enum):
    # Inbound
    PURCHASE_RECEIPT = "PURCHASE_RECEIPT"
    PRODUCTION_RECEIPT = "PRODUCTION_RECEIPT"
    SALES_RETURN_RECEIPT = "SALES_RETURN_RECEIPT"
    TRANSFER_RECEIPT = "TRANSFER_RECEIPT"
    ADJUSTMENT_IN = "ADJUSTMENT_IN"

    # Outbound
    SALES_SHIPMENT = "SALES_SHIPMENT"
    PRODUCTION_ISSUE = "PRODUCTION_ISSUE"
    PURCHASE_RETURN_SHIPMENT = "PURCHASE_RETURN_SHIPMENT"
    TRANSFER_ISSUE = "TRANSFER_ISSUE"
    INTERNAL_CONSUMPTION = "INTERNAL_CONSUMPTION"
    SCRAP = "SCRAP"
    ADJUSTMENT_OUT = "ADJUSTMENT_OUT"


class ReasonCode(str, Enum):
    CYCLE_COUNT = "CYCLE_COUNT"
    PHYSICAL_COUNT = "PHYSICAL_COUNT"
    DAMAGE = "DAMAGE"
    EXPIRY = "EXPIRY"
    QUALITY_REJECT = "QUALITY_REJECT"
    INTERNAL_USE = "INTERNAL_USE"
    SAMPLE = "SAMPLE"
    OTHER = "OTHER"


class ExtendedDocumentStatus(str, Enum):
    DRAFT = "DRAFT"
    REQUESTED = "REQUESTED"
    APPROVED = "APPROVED"
    RESERVED = "RESERVED"
    PARTIALLY_RESERVED = "PARTIALLY_RESERVED"
    IN_PROGRESS = "IN_PROGRESS"
    EXECUTED = "EXECUTED"
    PARTIALLY_EXECUTED = "PARTIALLY_EXECUTED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    POSTED = "POSTED"


class ReservationStatus(str, Enum):
    PENDING = "PENDING"
    RESERVED = "RESERVED"
    PARTIALLY_RESERVED = "PARTIALLY_RESERVED"
    RELEASED = "RELEASED"
    CONSUMED = "CONSUMED"
    EXPIRED = "EXPIRED"


class ExecutionStatus(str, Enum):
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    EXECUTED = "EXECUTED"
    PARTIALLY_EXECUTED = "PARTIALLY_EXECUTED"
    SHORT_CLOSED = "SHORT_CLOSED"
    REJECTED = "REJECTED"


INBOUND_TYPES = frozenset({
    TransactionType.PURCHASE_RECEIPT,
    TransactionType.PRODUCTION_RECEIPT,
    TransactionType.SALES_RETURN_RECEIPT,
    TransactionType.TRANSFER_RECEIPT,
    TransactionType.ADJUSTMENT_IN,
})

OUTBOUND_TYPES = frozenset({
    TransactionType.SALES_SHIPMENT,
    TransactionType.PRODUCTION_ISSUE,
    TransactionType.PURCHASE_RETURN_SHIPMENT,
    TransactionType.TRANSFER_ISSUE,
    TransactionType.INTERNAL_CONSUMPTION,
    TransactionType.SCRAP,
    TransactionType.ADJUSTMENT_OUT,
})

REQUIRES_RESERVATION = frozenset({
    TransactionType.SALES_SHIPMENT,
    TransactionType.PRODUCTION_ISSUE,
    TransactionType.TRANSFER_ISSUE,
})

REQUIRES_REASON_CODE = frozenset({
    TransactionType.ADJUSTMENT_IN,
    TransactionType.ADJUSTMENT_OUT,
    TransactionType.SCRAP,
    TransactionType.INTERNAL_CONSUMPTION,
})
