# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from lessons.gRPC.generate import robot_pb2 as robot__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in robot_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RobotControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateLocationStream = channel.stream_unary(
                '/wms_robot.RobotController/UpdateLocationStream',
                request_serializer=robot__pb2.RobotLocation.SerializeToString,
                response_deserializer=robot__pb2.EmptyResponse.FromString,
                _registered_method=True)
        self.ControlLoop = channel.stream_stream(
                '/wms_robot.RobotController/ControlLoop',
                request_serializer=robot__pb2.RobotLocation.SerializeToString,
                response_deserializer=robot__pb2.RobotCommand.FromString,
                _registered_method=True)


class RobotControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UpdateLocationStream(self, request_iterator, context):
        """Robot cập nhật vị trí, Server chỉ cần báo đã nhận (Ack)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ControlLoop(self, request_iterator, context):
        """Bi-directional stream: Cả 2 cùng gửi và nhận liên tục (Bài mới)
        Robot đổ tọa độ vào, Server đổ lệnh ra
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateLocationStream': grpc.stream_unary_rpc_method_handler(
                    servicer.UpdateLocationStream,
                    request_deserializer=robot__pb2.RobotLocation.FromString,
                    response_serializer=robot__pb2.EmptyResponse.SerializeToString,
            ),
            'ControlLoop': grpc.stream_stream_rpc_method_handler(
                    servicer.ControlLoop,
                    request_deserializer=robot__pb2.RobotLocation.FromString,
                    response_serializer=robot__pb2.RobotCommand.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wms_robot.RobotController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('wms_robot.RobotController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RobotController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpdateLocationStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/wms_robot.RobotController/UpdateLocationStream',
            robot__pb2.RobotLocation.SerializeToString,
            robot__pb2.EmptyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ControlLoop(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/wms_robot.RobotController/ControlLoop',
            robot__pb2.RobotLocation.SerializeToString,
            robot__pb2.RobotCommand.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
