# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: robot.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'robot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0brobot.proto\x12\twms_robot\".\n\nPickupTask\x12\x0e\n\x06sku_id\x18\x01 \x01(\t\x12\x10\n\x08location\x18\x02 \x01(\x05\"K\n\rPickupRespone\x12\x13\n\x0bis_complete\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t\x12\x15\n\rcomplete_time\x18\x03 \x01(\x05\"G\n\rRobotLocation\x12\x10\n\x08robot_id\x18\x01 \x01(\t\x12\x11\n\txlocation\x18\x02 \x01(\x05\x12\x11\n\tylocation\x18\x03 \x01(\x05\"\x0f\n\rEmptyResponse\"\x1e\n\x0cRobotCommand\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t2\xa5\x01\n\x0fRobotController\x12L\n\x14UpdateLocationStream\x12\x18.wms_robot.RobotLocation\x1a\x18.wms_robot.EmptyResponse(\x01\x12\x44\n\x0b\x43ontrolLoop\x12\x18.wms_robot.RobotLocation\x1a\x17.wms_robot.RobotCommand(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PICKUPTASK']._serialized_start=26
  _globals['_PICKUPTASK']._serialized_end=72
  _globals['_PICKUPRESPONE']._serialized_start=74
  _globals['_PICKUPRESPONE']._serialized_end=149
  _globals['_ROBOTLOCATION']._serialized_start=151
  _globals['_ROBOTLOCATION']._serialized_end=222
  _globals['_EMPTYRESPONSE']._serialized_start=224
  _globals['_EMPTYRESPONSE']._serialized_end=239
  _globals['_ROBOTCOMMAND']._serialized_start=241
  _globals['_ROBOTCOMMAND']._serialized_end=271
  _globals['_ROBOTCONTROLLER']._serialized_start=274
  _globals['_ROBOTCONTROLLER']._serialized_end=439
# @@protoc_insertion_point(module_scope)
