from __future__ import annotations

import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PROTO_ROOT = ROOT / "proto"


TARGETS = {
    "Services/identity-service": ("src/identity_service/gen", ["wms/identity"]),
    "Services/customer-service": ("src/customer_service/gen", ["wms/customer", "wms/identity"]),
    "Services/product-service": ("src/product_service/gen", ["wms/product", "wms/identity"]),
    "Services/warehouse-service": ("src/warehouse_service/gen", ["wms/warehouse", "wms/identity"]),
    "Services/inventory-service": ("src/inventory_service/gen", ["wms/inventory"]),
    "Services/documents-service": ("src/documents_service/gen", ["wms/documents", "wms/inventory"]),
    "Services/audit-service": ("src/audit_service/gen", ["wms/audit"]),
    "Services/reporting-service": ("src/reporting_service/gen", ["wms/reporting"]),
    "Services/ai-service": ("src/ai_service/gen", ["wms/ai"]),
    "Services/api-gateway": ("src/api_gateway/gen", [""]),  # Gateway needs everything.
}

def fix_generated_imports(path: Path) -> None:
    """
    Fixes the broken absolute imports generated by protoc in Python.
    Changes 'import wms...' to relative imports if necessary.
    """
    for p in path.rglob("*_pb2*.py"):
        with open(p, "r", encoding="utf-8") as f:
            content = f.read()

        # Replace absolute imports of our own proto packages with relative ones
        # This fixes ModuleNotFoundError when 'gen' is not in PYTHONPATH
        new_content = re.sub(
            r"from wms\.(.*) import (.*)_pb2 as (.*)",
            r"from . import \2_pb2 as \3",
            content
        )
        
        with open(p, "w", encoding="utf-8") as f:
            f.write(new_content)

def main() -> None:
    for service_dir, (out_dir, proto_subpaths) in TARGETS.items():
        # Filter protos based on service domain, or take all if subpath is empty (for gateway)
        service_protos: list[str] = []
        for proto_subpath in proto_subpaths:
            search_path = PROTO_ROOT / proto_subpath
            service_protos.extend(str(p) for p in search_path.rglob("*.proto"))
        
        if not service_protos:
            print(f"Skipping {service_dir}: No protos found in {proto_subpaths}")
            continue

        out_path = ROOT / service_dir / out_dir
        out_path.parent.mkdir(parents=True, exist_ok=True)
        temp_path = Path(tempfile.mkdtemp(prefix=f"{out_path.name}-", dir=out_path.parent))

        cmd = [
            sys.executable,
            "-m",
            "grpc_tools.protoc",
            f"-I{PROTO_ROOT}",
            f"--python_out={temp_path}",
            f"--grpc_python_out={temp_path}",
            *service_protos,
        ]
        try:
            subprocess.check_call(cmd)
        
            # Fix potential import issues within the generated files
            fix_generated_imports(temp_path)

            # Swap only after generation succeeds so a failed protoc run never
            # leaves a service with an empty gen package.
            shutil.rmtree(out_path, ignore_errors=True)
            shutil.move(str(temp_path), str(out_path))
        except Exception:
            shutil.rmtree(temp_path, ignore_errors=True)
            raise


if __name__ == "__main__":
    main()
